[package]
name = "potionkeeper"
version = "0.1.0"
edition = "2021"

[dependencies]
potionforge = { path = "../potionforge" }
clap = { version = "4.4.5", features = ["cargo"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
prettytable-rs = "0.8.0"
